/* autogenerated by ./tools/mkoffsets, do not edit */
#define OFS_DrawScanline     0x00
#define OFS_rendstatus       0x04
#define OFS_DrawLineDest     0x08
#define OFS_HighCol          0x0c
#define OFS_HighPreSpr       0x10
#define OFS_Pico_video       0x14
#define OFS_Pico_vram        0x18
#define OFS_PicoOpt          0x1c
#define OFS_Draw2FB          0x20
#define OFS_HighPal          0x24
